### ISSUE TITLE
GAMDAM: duplicates in GLIMS

### ISSUE THREAD

**Issue by fmaussion** [GLIMS-RGI/glims_issue_tracker#10]
Anlys ID pairs which are strictly equivalent:
812271 812282
812315 812321
813707 813708
813938 813939

Anlys ID pairs which are on the same spot but not exact same (need to pick one):
905959 905963
905976 905985
836228 836234
836293 836294
844349 844364

**Comment by bruceraup** [comment]
I removed the following analysis IDs:

812282
812321
813708
813939
905959
905976
836234
836293
844349
