### ISSUE TITLE
Nominal glaciers in RGI6 made it into GLIMS 

### ISSUE THREAD

**Issue by burnout-stephl** [GLIMS-RGI/glims_issue_tracker#6]
Working on the RGI7a file for Region 10 (North Asia) I noticed that there are still nominal glaciers in the GLIMS data base as part of RGI6 data (subm_id 636). 
I do not know if this is a mistake or if this was done intentionally.  
However, for RGI7a I just omitted all 116 nominal glaciers of this region which are all located on Wrangel Island and islands in the Sibirian Sea.
We will also discuss implications of this issue in the discussion of the RGI7a region files.

**Comment by fmaussion** [comment]
These are filtered out in RGI7 but still in GLIMS:

![image](https://user-images.githubusercontent.com/10050469/150175257-1aa4e1a6-7e3e-4f9b-802c-fc6ca699a950.png)

**Comment by fmaussion** [comment]
Trello: https://trello.com/c/EomH6r0D

**Comment by bruceraup** [comment]
Deleted these circular polygons from GLIMS.  Am reseeding the geoserver cache now.
