### ISSUE TITLE
RGI06 for Reg07- Svalbard and Jan Mayen not reproducible from GLIMS data base

### ISSUE THREAD

**Issue by burnout-stephl** [GLIMS-RGI/glims_issue_tracker#7]
I just tried to produce rgi7a for RGI region 07. While glaciers on Jan-Mayen are represented by subm_id 718, there is no submission corresponding to RGI6 for Svalbard. Subm_id 563 is very similar to RGI6 but there are a few (~15) smaller glaciers in subm_id 563 which were not part of RGI6. Besides that there are a number of outlines which were modified in one of the two data-sets.
Figure below shows RGI6 (grey) over subm_id 563 (red) which is almost the same than RGI6 but contains a bunch of small 'glaciers' not part of RGI6...  

   
![svalbard](https://user-images.githubusercontent.com/57042208/125428508-a23b6f87-db18-4736-aaf2-b32856f0cb29.png)

**Comment by fmaussion** [comment]
I have looked into this and I'm not sure why they are removed from RGI. GLIMS seems fine there.

**Comment by fmaussion** [comment]
![image](https://user-images.githubusercontent.com/10050469/145692873-1c968da2-b964-4d10-9490-e4a71d89b7d2.png)

![image](https://user-images.githubusercontent.com/10050469/145692878-57789cbf-c871-4b40-b611-eb753f4e0bd1.png)
